version: '2'
services:
    jhipmongotest-app:
        image: jhipmongotest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipmongotest-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipmongotest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipmongotest-mongodb:
        extends:
            file: mongodb.yml
            service: jhipmongotest-mongodb
